.PHONY: clean All

All:
	@echo "----------Building project:[ odin - Debug ]----------"
	@cd "odin" && "$(MAKE)" -f  "odin.mk"
	@echo "----------Building project:[ telnetpp - Debug ]----------"
	@cd "telnetpp" && "$(MAKE)" -f  "telnetpp.mk"
	@echo "----------Building project:[ terminalpp - Debug ]----------"
	@cd "terminalpp" && "$(MAKE)" -f  "terminalpp.mk"
	@echo "----------Building project:[ septem - Debug ]----------"
	@cd "septem" && "$(MAKE)" -f  "septem.mk"
clean:
	@echo "----------Cleaning project:[ odin - Debug ]----------"
	@cd "odin" && "$(MAKE)" -f  "odin.mk"  clean
	@echo "----------Cleaning project:[ telnetpp - Debug ]----------"
	@cd "telnetpp" && "$(MAKE)" -f  "telnetpp.mk"  clean
	@echo "----------Cleaning project:[ terminalpp - Debug ]----------"
	@cd "terminalpp" && "$(MAKE)" -f  "terminalpp.mk"  clean
	@echo "----------Cleaning project:[ septem - Debug ]----------"
	@cd "septem" && "$(MAKE)" -f  "septem.mk" clean
