.PHONY: clean All

All:
	@echo "----------Building project:[ septem - Debug ]----------"
	@cd "septem" && "$(MAKE)" -f  "septem.mk"
clean:
	@echo "----------Cleaning project:[ septem - Debug ]----------"
	@cd "septem" && "$(MAKE)" -f  "septem.mk" clean
